application: polymer-gopher
module: frontend
version: v1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static